riscv-c-api.md

Defined when -mabi=ilp32e is used.

Add new __riscv_abi_rve macro.

---

riscv-c-api.md

We have assembler ports for the V and B extensions, so we should be thinking about adding preprocessor macros for them.  __riscv_vector seems straightforward.  __riscv_bitmanipulation seems inconveniently long, but __riscv_bitmanip looks OK, and is consistent with the B extension gas/gcc patches.  I asked in a riscv/riscv-bitmanip issue if they are OK with this.  We should wait for comments in case they want to suggest something different.

Add __riscv_vector and __riscv_bitmanip for V and B extensions.

---

riscv-c-api.md

The motivation of this scheme is have an unify naming scheme for
extension macro and add the capability to checking version.
The new naming scheme is `__riscv_<extension name>`, and it will define
the value to `<MAJOR_VERSION> * 1,000,000 + <MINOR_VERSION> * 1,000 + <REVISION_VERSION>`
For example:
- F-extension v2.2 will define `__riscv_f` as `20002000`.
- B-extension v0.92 will define `__riscv_b` as `92000`.
We also introduce a new macro `__riscv_arch_test_marco` to check this
test marco set is available.

Introduce new scheme of extension related predefined macro

---

riscv-c-api.md

We don't have a single B/Bitmanip extension, but several extensions
Zb[abcs], which can be available independent of each other.
Let's fix that in this document.
Given that there was never a ratified Bitmanip extensions,
I don't think that this change causes any real-world problems.
@kito-cheng @jim-wilson @asb

Use Zb[abcs] instead of B/Bitmanip

---

riscv-c-api.md

After adding the zve extension it is not obvious for user whether if there is
any vector instructions available. Adding __riscv_vector will let the users
able to check this.

Add __riscv_vector back from deprecated

---

riscv-c-api.md

Changes:
2021/08/19: Apply Fraser's fix.
2021/08/19: Change prefix to `__riscv_v_`
---
Background
RVV 1.0 has add few more extension (`zvl*b` and `zve*`) to give the promise about the EEW and VLEN, and this PR intend to expose those info by predefined marco.
https://github.com/riscv/riscv-v-spec/blob/master/v-spec.adoc#sec-vector-extensions
---
Introduce `__riscv_v_min_vlen`, `__riscv_v_max_eew` and `__riscv_v_max_eew_fp`
macro, for let programer easier to get vector related information, like:
- What's the minimal VLEN value is guaranteed current architecture
extension?
- What's the maximal available EEW is guaranteed current
architecture extension?
- What's the maximal available EEW for floating-point operation is
guaranteed current architecture extension?
It's possible to get the …

Add misc macro for vector extensions.

---

riscv-c-api.md

Let's establish a naming guideline for intrinsics.
Contrary to the previous attempt in #25, this PR does not try to make a guideline that covers all existing formats but defines a single new format.

Intrinsics: Define intrinsics naming guidelines

---

riscv-c-api.md

We have 3 common operand constraints constraint between GCC and LLVM here:
- vr: Any vector register, v0-v31
- vd: Any vector register, excluding v0, used for avoid overlapping with mask register.
- vm: Mask vector register, only v0.

Add inline asm operand constraints for vector register

---

riscv-c-api.md

We have few RISC-V specific function attributes like naked and interrupt, they are implmented on both LLVM and GCC for a while.
But we don't have well described here.

Add more description for those function attributes

---

riscv-c-api.md

The intrinsic section tried to write __riscv_ but the two underscores were being parsed by markdown.
This patch changes the quotation marks around the string to backticks to it will show as code instead. Alternatively, I can escape the underscore if we want the quotation marks.

Prevent 2 underscores from being interpreted as italics

---

riscv-c-api.md

This is a proposal for zihintntl intrinsic function.

zihintntl Intrinsic function proposal

---

riscv-c-api.md

The current description might give some people the impression that misaligned accesses are only a little bit slower than aligned ones.  But the intent is for the "slow" macro to be defined when the accesses are legal, but potentially extremely slow.
By contrast, the "fast" macro should be defined when misaligned accesses are reasonably fast, even if they're a little bit slower than misaligned ones.  So, the existing text for the "fast" case is fine.
This isn't really a normative change; it's a tweak to the shades of meaning in the description.

Clarify that slow misaligned accesses may be very slow

---

riscv-c-api.md

This patch defines an availability macro for the Zawrs extension.
Note, that Zawrs is not frozen or ratified yet. I.e. this is an RFC for the time being.

Zawrs: Define extension availability macro

---

riscv-c-api.md

- Document `z` and `i`, which has implemented on both LLVM and GCC.
---
@topperc fixed a GCC compatible issue on `r` constraint with 0 immediate[1], and I found we didn't well document those operand modifier any where including GCC document...so I think it would be great to start document this some where, and here should be a good starter.
[1] https://reviews.llvm.org/D154744
cc @asb

Document operand modifier

---

riscv-c-api.md

After adding mapping symbol and `.option arch`, finally we have
all necessary components of function multi-versioning.
This proposal has add a new funciton attribte: `target` attribte for compile a
funciton with specify extension, pipeline model or cost model, could be used as
simple`*` function multi-versioning.
`*`: Simple is compare to `target_clones` in x86 and `target_version` in
AArch64, and also require user to dispatch that right.
It similar to AArch64's target attribte: https://gcc.gnu.org/onlinedocs/gcc/AArch64-Function-Attributes.html
This attribte won't change the function name mangling, and also require
do not update Tag_RISCV_arch attribte.
Ref:
- https://maskray.me/blog/2023-02-05-function-multi-versioning
---
NOTE: This PR will not be merged until we have PoC *AND* …

Adding target attribute for function.

---

riscv-c-api.md

This is a proposal for scalar crypto intrinsics for the Zk* extensions.
I've removed the recommendation to use 'long' for XLEN. There's nothing guaranteeing that 'long' is XLEN. For example, if we were to support ILP32 on RV64, 'long' would become 32 bits while XLEN would still be 64 bits.
Other design decisions are spelled out in the document.
Some text has been copied from #23.
One open question is whether we should emulate 64-bit intrinsics on RV32 where it is feasible.  This could be useful for the sha512 intrinsics and some others.
@cmuellner @kito-cheng @mjosaarinen

Scalar bitmanip and crypto intrinsics proposal

---

riscv-c-api.md

Adds the __riscv_zicsr and __riscv_zifencei extension test macros to the existing table.
cc @kito-cheng

Add zicsr and zifencei to extension test macros

---

riscv-c-api.md

`__riscv_64e` is defined analogously to `__riscv_32e`.
Changing the meaning of `__riscv_32e` should not cause any problems since if we are just testing for existence of the `E` extension, there is `__riscv_e` preprocessor macro.

Add support for RV64E and LP64E

---

riscv-c-api.md

These should be __riscv_sha512sum0r and __riscv_sha512sum1r. There are only 2 instructions not 4.

Fix the  __riscv_sha512sum0/1 intrinsics for RV32.

---

riscv-c-api.md

ARM[1] provide the its own semantic on prefetch built-in locality.
It seem we could do the same thing in RISC-V.
[1] https://developer.arm.com/documentation/101458/2010/Coding-best-practice/Prefetching-with---builtin-prefetch

Locality for prefetch built-in proposal

---

riscv-c-api.md

These should be  __riscv_clmul*(uintxlen_t rs1, uintxlen_t rs2). There are only 1 argument.

Fix the __riscv_clmul* intrinsics.

---

riscv-c-api.md

Added support for Zimop extension.
For both open-source compilers: GCC and Clang already prepared corresponding patches. Going to publish them.
cc: @kito-cheng

Added support for zimop extension

---

riscv-c-api.md

This fixes a simple copy-paste mistake in the orc_b_32 emulation comment for rv64.

Bitmanip intrinsics: Fix orc_b_32 emulation comment for rv64

---

riscv-c-api.md

The Q extension and its `__riscv_q` predefined macro are missing from the list, but compilers do actually define this alongside `__riscv_f` and `__riscv_d`.

Add missing `__riscv_q` predefine to riscv-c-api.md

---

riscv-c-api.md

This attempts to rework the extension test macros section and drop the useless (and incomplete) extension test macro list.
Previous attempts to clean up this section can be found in #27 and #28.
This should avoid the need for PRs like #55 that add something obvious done by GCC and LLVM without the need for this list. Further, we recently also discussed this in the context of #44 (adding bitmap and scalar crypto extensions to the list). So I think it is time to remove the list.

Rework the extension test macros section

---

riscv-c-api.md

"s" can be used to create an artificial reference for linker garbage collection, or define sections to hold symbol addresses. "S" does not work for a preemptible symbol in GCC while "s" does.

Document constraint "s"

---

riscv-c-api.md

Standard vector calling convention variant has landed in psABI now, and the implementation also merged into GCC trunk, LLVM part are also under reviewing, and this attribute has mentioned during the discussion, but seems like we don't document that yet.
---
Standard vector calling convention variant will only enabled when function has vector argument or returing value by default, however user may also want to invoke function without that during a vectorized loop at some situation, but it will cause a huge performance penalty due to vector register store/restore.
So user can declare function with this riscv_vector_cc attribute like below, that could enforce function will use standard vector calling convention variant.
```c
void foo() __attribute__((riscv_vector_cc));
[[riscv::vector_cc]] …
```

Function attribute for standard vector calling convention variant: riscv_vector_cc

---

riscv-c-api.md

During the Function multi-version dispatch the function, we need a method to retrieve the RISC-V hardware environment to make sure all extension must be available.
The problem is
* How to implement this function
* Where to provide this function
From the compiler's view, it will generate the IFUNC resolver when there are more than one implementation with the same symbol name.
Consider following example:
```
__attribute__((target("default"))) int foo (int index)
{
return index;
}
__attribute__((target("arch=rv64gc"))) int foo (int index)
{
return index;
}
void bar() {
foo(0);
}
```
The corresponding assembly will look like:
```
bar() {
(foo.ifunc())(0);
}
.set foo.ifunc, foo.resolver
func_ptr foo.resolver() {
if (__riscv_ifunc_select("m_a_f_d_c"))
return ptr foo.m_a_f_d_c;
return ptr …
```

Function multi-version proposal

---

riscv-c-api.md

This seems to the direction we're moving -mstrict-align/-mno-strict-align towards.

Update __riscv_misaligned_* macros to refer to scalar only

---

src/c-api.adoc

With https://github.com/riscv-non-isa/riscv-elf-psabi-doc/pull/388 landed it makes sense to have a define for the large code model for consistency with medany and medlow.

Add __riscv_cmodel_large define for large code model

---

src/c-api.adoc

This PR proposes a runtime resolver function that retrieves the environment information. Since this resolver function is expected to be available and interchangeable for both `libgcc` and `compiler-rt`, a formal specification for the resolver function interface is necessary.
---
When generating the resolver function for function multiversioning, a mechanism is necessary to obtain the environment information.
To achieve this goal, several steps need to be taken:
1. Collect the required extensions for a particular function.
2. Transform these required extensions into a platform-dependent form.
3. Query whether the environment fulfills these requirements during runtime.
Step 1 is handled by the compiler, while step 3 must follow the necessary steps from the platform during runtime.
This RFC …

[FMV] Runtime Resolver Function

---

src/c-api.adoc

PR #74 introduced __riscv_cpu_model data struct for Function Multi-Versioning.
However, unlike fixed 32-bit mvendorid CSR, marchid and mimpid are MXLEN-sized CSR. The Linux kernel will also return these in u64 type, which takes a `long` typed value from MXLEN-sized SBI ecall. I think it's better to turn these fields to `unsigned long long` instead of  `unsigned`. It's still possible to make this change since these codes were only implemented in LLVM, but they now have no users.

[FMV] use long long type for marchid and mimpid

---

src/c-api.adoc

We have customers with usecases that want more kinds of register
constraints and modifiers. This change proposes support for these
constraints and modifiers, and their names.
Broadly, these are intended to make it easier for users who want to
manually assemble instructions inside inline assembly blocks, either
using the existing instruction formats, or using the raw form of the
`.insn` directive. This makes it easier for hardware designers to
experiment on new ISA extensions, and makes it easier to support
the use of proprietary extensions with unmodified open-source
toolchains.
There are three groups of additions here:
- Constraints for RVC-compatible registers. These use the `c` prefix on
an existing register constraint, so `cr` gives a GPR between x8-x15,
and `cf` does the same for an …

Inline Asm Constraints and Modifiers - RVC, Raw Encodings, Pairs

---

src/c-api.adoc

The new CI/CD steps complain about a trailing whitespace. Let's remove that.

c-api: Remove trailing whitespace

---

src/c-api.adoc

Function multi-versioning provides several versions to choose from. When selecting the appropriate version, there are two factors that impact this process. First is whether a version is eligible. Second is the order in which all eligible versions are tried. For other targets (like aarch64), a priority number is defined for each feature. In this PR, we propose new syntax that allows users to define their own priority for specific versions.
The version selection process applies the following rules in order:
1. Among the eligible versions, select the one with the highest priority.
2. If multiple versions have equal priority, select the one that was declared first.
3. If no other suitable versions are found, fall back to the "default" version.

[FMV] Add `Priority` syntax for version selection order

---

src/c-api.adoc

As discussed in #96, current interface is insufficient to support some cases, like a vendor buying a CPU IP from the upstream vendor but using their own mvendorid and custom features from the upstream vendor. In this case, we might need to add these extensions for each downstream vendor many times. Thus, making __riscv_vendor_feature_bits guarded by mvendorid is not a good idea. So, drop __riscv_vendor_feature_bits for now, and we should have time to discuss a better solution.

Drop __riscv_vendor_feature_bits

---

src/c-api.adoc

Zilsd, Zclsd and Zcmp are ratified standard extensions which lack bit assignments. I've just appended them to the end.
Note that Zcmop, which is already listed next to the non-Zcmp Zce extensions, is its own extension, not a typo for Zcmp.
For context, I'm considering exposing this bit mask through a custom M-mode CSR  on an embedded-class core to list hardware capabilities with finer granularity than `misa`, but less complexity than the configuration struct or device tree. I implement the three extensions added by this PR.

Add Zilsd, Zclsd, Zcmp to Extension Bitmask

---

src/c-api.adoc

This follows the notion of using `c` as a prefix to mean "RVC-compatible", and `R` to mean "even-odd GPR Pair".
The Zclsd specification adds registers with this constraint, in particular the `c.ld` and `c.sd` instructions need it.

Add RVC GPR Pair Constraint - `cR`

---

src/c-api.adoc

This adds the bits that are defined already in `misa.Extensions`, in the privileged spec, following the note above the table, and existing ratified extensions.
While we would not expect all of these to be present in an OS-level hwcap interface (for example the H bit), I think it is fine to allocate these for the single-letter part of the bitmask, so these bits are not otherwise used.
---
This follows #107 in finishing defining the single-letter extensions that are defined so far.

Add Defined misa Bits

---

src/c-api.adoc

These have been removed from both GCC and Clang, because the underlying N extension they were based on was never ratified.
This change also relaxes some of the requirements, to allow vendor interrupt modes, and combinations of (compatible) interrupt modes, which matches the LLVM implementation of SiFive interrupts.

Remove User Interrupts, Relax Requirements
